export type ApiErrorCode =
  | 'INVALID_INSTAGRAM_URL'
  | 'INVALID_YOUTUBE_URL'
  | 'PLAYLIST_NOT_SUPPORTED'
  | 'PRIVATE_OR_UNAVAILABLE'
  | 'LOGIN_REQUIRED'
  | 'RATE_LIMITED'
  | 'SERVER_BUSY'
  | 'PROVIDER_CHALLENGE'
  | 'TOKEN_PROVIDER_UNAVAILABLE'
  | 'EXTRACTION_TIMEOUT'
  | 'EXTRACTION_FAILED'
  | 'PROVIDER_UNAVAILABLE'
  | 'TOKEN_PROVIDER_UNAVAILABLE'
  | 'PROVIDER_MALFORMED_RESPONSE'
  | 'INVALID_TOKEN'
  | 'EXPIRED_TOKEN'
  | 'MEDIA_NOT_FOUND'
  | 'MEDIA_UNAVAILABLE'
  | 'MEDIA_TOO_LARGE'
  | 'UPSTREAM_TIMEOUT'
  | 'UPSTREAM_INVALID_CONTENT'
  | 'DOWNLOAD_FAILED'
  | 'MEDIA_TOO_LONG'
  | 'PRIVATE_MEDIA'
  | 'AGE_RESTRICTED'
  | 'LIVE_NOT_AVAILABLE'
  | 'DRM_UNSUPPORTED'
  | 'UNSUPPORTED_MEDIA'
  | 'INTERNAL_ERROR';

export class ApiError extends Error {
  constructor(
    public readonly code: ApiErrorCode,
    message: string,
    public readonly statusCode: number,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}
